version: '3'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=0rd3rY0ur0wnF00d
    ports:
      - 1433:1433
    volumes:
      - db-data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
      
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data

  apigate:
    build:
      context: .
      dockerfile: dockerfileGateway
    image: api_gateway:latest
    ports:
      - 5005:8080
    links:
      - kitchen
      - order
    depends_on:
      - sql-server
      - rabbitmq
      - sonarqube
      - kitchen
      - order

  kitchen:
    build:
      context: .
      dockerfile: dockerfileKitchen
    hostname: kitchen
    image: kitchen_image:latest
    links:
      - order
    depends_on:
      - sql-server
      - rabbitmq
      - sonarqube

  order:
    build:
      context: .
      dockerfile: dockerfileOrder
    hostname: order
    image: order_image:latest
    links:
      - kitchen
    depends_on:
      - sql-server
      - rabbitmq
      - sonarqube

volumes:
  db-data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data: